Update actions (#5)
Signed-off-by: Knative Automation <automation@knative.team>

diff --git a/.github/workflows/knative-verify.yaml b/.github/workflows/knative-verify.yaml
--- a/.github/workflows/knative-verify.yaml
+++ b/.github/workflows/knative-verify.yaml
@@ -27,8 +27,8 @@ jobs:
     name: Verify Deps and Codegen
     strategy:
       matrix:
-        go-version: [ 1.16.x ]
-        platform: [ ubuntu-latest ]
+        go-version: [1.16.x]
+        platform: [ubuntu-latest]
 
     runs-on: ${{ matrix.platform }}
 
@@ -37,52 +37,52 @@ jobs:
 
     steps:
 
-      - name: Set up Go ${{ matrix.go-version }}
-        uses: actions/setup-go@v2
-        with:
-          go-version: ${{ matrix.go-version }}
-        id: go
+    - name: Set up Go ${{ matrix.go-version }}
+      uses: actions/setup-go@v2
+      with:
+        go-version: ${{ matrix.go-version }}
+      id: go
 
-      - name: Install Dependencies
-        run: |
-          curl -L https://github.com/google/ko/releases/download/v0.6.0/ko_0.6.0_Linux_x86_64.tar.gz | tar xzf - ko
-          chmod +x ./ko
-          sudo mv ko /usr/local/bin
-          go get github.com/google/go-licenses
+    - name: Install Dependencies
+      run: |
+        curl -L https://github.com/google/ko/releases/download/v0.6.0/ko_0.6.0_Linux_x86_64.tar.gz | tar xzf - ko
+        chmod +x ./ko
+        sudo mv ko /usr/local/bin
+        go get github.com/google/go-licenses
 
-      - name: Check out code onto GOPATH
-        uses: actions/checkout@v2
-        with:
-          path: ./src/knative.dev/${{ github.event.repository.name }}
+    - name: Check out code onto GOPATH
+      uses: actions/checkout@v2
+      with:
+        path: ./src/knative.dev/${{ github.event.repository.name }}
 
-      - name: Update Codegen
-        shell: bash
-        run: |
-          pushd ./src/knative.dev/${{ github.event.repository.name }}
-          [[ ! -f hack/update-codegen.sh ]] || ./hack/update-codegen.sh
-          popd
+    - name: Update Codegen
+      shell: bash
+      run: |
+        pushd ./src/knative.dev/${{ github.event.repository.name }}
+        [[ ! -f hack/update-codegen.sh ]] || ./hack/update-codegen.sh
+        popd
 
-      - name: Verify
-        shell: bash
-        run: |
-          # From: https://backreference.org/2009/12/23/how-to-match-newlines-in-sed/
-          # This is to leverage this workaround:
-          # https://github.com/actions/toolkit/issues/193#issuecomment-605394935
-          function urlencode() {
-            sed ':begin;$!N;s/\n/%0A/;tbegin'
-          }
+    - name: Verify
+      shell: bash
+      run: |
+        # From: https://backreference.org/2009/12/23/how-to-match-newlines-in-sed/
+        # This is to leverage this workaround:
+        # https://github.com/actions/toolkit/issues/193#issuecomment-605394935
+        function urlencode() {
+          sed ':begin;$!N;s/\n/%0A/;tbegin'
+        }
 
-          pushd ./src/knative.dev/${{ github.event.repository.name }}
-          if [[ -z "$(git status --porcelain)" ]]; then
-              echo "${{ github.repository }} up to date."
-          else
-              # Print it both ways because sometimes we haven't modified the file (e.g. zz_generated),
-              # and sometimes we have (e.g. configmap checksum).
-              echo "Found diffs in: $(git diff-index --name-only HEAD --)"
-              for x in $(git diff-index --name-only HEAD --); do
-                  echo "::error file=$x::Please run ./hack/update-codegen.sh.%0A$(git diff $x | urlencode)"
-              done
-              echo "${{ github.repository }} is out of date. Please run hack/update-codegen.sh"
-              exit 1
-          fi
-          popd
+        pushd ./src/knative.dev/${{ github.event.repository.name }}
+        if [[ -z "$(git status --porcelain)" ]]; then
+            echo "${{ github.repository }} up to date."
+        else
+            # Print it both ways because sometimes we haven't modified the file (e.g. zz_generated),
+            # and sometimes we have (e.g. configmap checksum).
+            echo "Found diffs in: $(git diff-index --name-only HEAD --)"
+            for x in $(git diff-index --name-only HEAD --); do
+                echo "::error file=$x::Please run ./hack/update-codegen.sh.%0A$(git diff $x | urlencode)"
+            done
+            echo "${{ github.repository }} is out of date. Please run hack/update-codegen.sh"
+            exit 1
+        fi
+        popd
